[project]
name = "html_synth_img"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets==4.4.1",
    "diffusers",
    "flash-attn",
    "jinja2==3.1.6",
    "kanjize==1.6.1",
    "opencv-python==4.12.0.88",
    "pillow==12.0.0",
    "playwright==1.56.0",
    "qwen-vl-utils==0.0.14",
    "scipy==1.16.2",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "transformers==4.57.3",
    "vllm==0.11.0",
]

[tool.uv.sources]
diffusers = { git = "https://github.com/huggingface/diffusers" }
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
flash-attn = { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.1/flash_attn-2.8.1+cu12torch2.8cxx11abiFALSE-cp312-cp312-linux_x86_64.whl" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
